name: Radicale
description: CalDAV and CardDAV Server
license: GPLv3
public: true
url: http://www.radicale.org/
pystil: https://kozea.pystil.org/pystil.js

menu:
  - News:
      link: /news/
  - Documentation:
      link: /documentation/
  - Contribute:
      link: /contribute/
  - Download:
      link: /download/

footer:
  - A Kozea Project:
      link: http://community.kozea.fr/
  - Optimized for Standards:
      link: http://validator.w3.org/check?uri=referer

project (git):
  url: git://github.com/Kozea/Radicale.git
  path: radicale

code browser (github):
  project name: Kozea/Radicale
  ribbon: Fork me on GitHub

bug tracker (github):
  project name: Kozea/Radicale

mailing list (librelist):
  project name: radicale

continuous integration (jenkins):
  base url: http://jenkins.kozea.org/
  project name: Radicale
