name: Radicale
description: CalDAV and CardDAV Server
license: GPLv3
public: true
url: http://www.radicale.org/

menu:
  - News:
      link: /news/
  - Documentation:
      link: /documentation/
  - Contribute:
      link: /contribute/
  - Download:
      link: /download/

project (git):
  url: git://github.com/Kozea/Radicale.git
  path: radicale

vcs (git):
  url: git://github.com/Kozea/Radicale.git
  path: /var/db/git/radicale.git

code browser (github):
  project name: Kozea/Radicale

bug tracker (redmine):
  base url: http://redmine.kozea.fr/
  project name: radicale

mailing list (librelist):
  project name: radicale

continuous integration (jenkins):
  base url: http://jenkins.kozea.org/
  project name: Radicale

# room (jabber):
#   address: radicale@room.jabber.kozea.fr

# package repository (pypi):
#   project name: radicale
